const ROUTER = '/';
const ROUTER_404 = '/404';
const ROUTER_500 = '/500';
const ROUTER_CHECKOUT = '/checkout';
const ROUTER_SELECT_PAYMENT = '/payment';
const ROUTER_SHOW = '/show';
const ROUTER_VINID_PAYMENT = '/vinid';
const ROUTER_NAPAS_PAYMENT = '/napas';

export { ROUTER, ROUTER_404, ROUTER_500, ROUTER_CHECKOUT, ROUTER_SELECT_PAYMENT, ROUTER_SHOW, ROUTER_VINID_PAYMENT, ROUTER_NAPAS_PAYMENT };
